In [23]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from math import floor

In [24]:
df = pd.DataFrame({"data" : [13,10,18,15,np.nan,25,13,20,20,15]})
df

   data
0  13.0
1  10.0
2  18.0
3  15.0
4   NaN
5  25.0
6  13.0
7  20.0
8  20.0
9  15.0

In [25]:
imputer = SimpleImputer(add_indicator=True)
df = imputer.fit_transform(df)
pd.DataFrame(df)

           0    1
0  13.000000  0.0
1  10.000000  0.0
2  18.000000  0.0
3  15.000000  0.0
4  16.555556  1.0
5  25.000000  0.0
6  13.000000  0.0
7  20.000000  0.0
8  20.000000  0.0
9  15.000000  0.0